### ISSUE TITLE
PA Review: User Authentication

### ISSUE THREAD

**Issue by chanmike92** [chanmike92/disMike#1]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by mashuDuek** [comment]
Your auth feature is done, per what we discussed via slack. And I know that, but now I go into your app and I am logged in, but I cannot log out to re-test this feature. Fix this please :).
